"""Add FCM token to User

Revision ID: db36bcf15f80
Revises: 1bb4b8ae7607
Create Date: 2025-04-19 03:32:48.832587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db36bcf15f80'
down_revision = '1bb4b8ae7607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')

    # ### end Alembic commands ###
